name: tic-tac-toe CI/CD

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: testing tic-tac-toe application
        run: echo "Tic-tac-toe Working!..."

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: caleb9083/tic-tac-toe
          tags: latest
          registry: docker.io
          dockerfile: ./tic-tac-toe/Dockerfile
          directory: ./tic-tac-toe/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps: 
      - name: Remove previous Image
        run: sudo docker rmi caleb9083/tic-tac-toe
        
      - name: Pulling the latest version of Image
        run: sudo docker pull caleb9083/tic-tac-toe
      
      - name: Take down previous container
        run: sudo docker rm -f tic-tac-toe

      - name: Create container
        run: sudo docker run -d -p 3000:3000 --name tic-tac-toe caleb9083/tic-tac-toe
