name: node-prometheus CI/CD

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: testing node-prometheus application
        run: echo "Node Prometheus Working!..."

      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: caleb9083/node-prometheus
          tags: latest
          registry: docker.io
          dockerfile: ./node-prometheus/Dockerfile
          directory: ./node-prometheus/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps: 
      - name: Pulling the latest version of Image
        run: sudo docker pull caleb9083/node-prometheus
      
      - name: Take down previous container
        run: sudo docker rm -f node-prometheus

      - name: Create container
        run: sudo docker run -d -p 8080:8080 --name node-prometheus caleb9083/node-prometheus
            
