name: CI

on:
  push:
    branches: [node-prometheus]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: testing node-prometheus application 
        run: echo "Node Prometheus Working!..."
