name: CI

on:
  push:
    branches: [node-prometheus]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: testing node-prometheus application
        run: echo "Node Prometheus Working!..."

      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: caleb9083/node-prometheus
          tags: v1, latest
          registry: docker.io
          dockerfile: ./node-prometheus/Dockerfile
          directory: ./node-prometheus/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
