name: Polls-app CI

on:
  push:
    branches: [polls-app]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: testing tic-tac-toe application
        run: echo "Polls-app Working!..."

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: caleb9083/polls-app
          tags: latest
          registry: docker.io
          dockerfile: ./polls-app/Dockerfile
          directory: ./polls-app/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
